### ISSUE TITLE
• Registration

### ISSUE THREAD

**Issue by DubstDisk** [AnimeHrus/Neko-Days#1]
Registration
`To do List`

> 1. **Fix** bug associated with overlapping boxes (Blackout objects when they are in mouse focus)
> 2. **Remove** animation Rotate-Button object (Refresh Ava'rs) 
> 3. Opportunity **choose** Avatar by clicking on it
> 4. **Workable** lists like a Day-List, month-list etc.
> 5. Password (******)
> 6. Error of incorrect password repetition
> 7. **Normalize** switch between Sing Up and Login
> 8. **Opportunity** upload Ava'rs
> 9. **Save** information about Registered Account 
> 10. **Choose & Delete** accounts
> 11. **Remove** Avatar by clicking on delete-cross buttom.

`DubDisk`

**Comment by AnimeHrus** [comment]
Incorrectly constructed issue.
